version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: localhost
    ports:
      - '${DB_SERVER_PORT:-5432}:3306'
    environment:
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strongpassword}
      POSTGRES_DATABASE: ${DB_DATABASE:-article-newsletter-auth}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: 
